### ISSUE TITLE
Use one name for npm package, cli, and github repo

### ISSUE THREAD

**Issue by pachun** [TheGnarCo/gnar-cli#15]
It's confusing that the command line command is `gnar`, the npm package is `gnar-cli`, and the repository name is `gnar-node-cli`. Already lost a few minutes over it.

I like that the CLI uses only `gnar`, but looks like someone has the `gnar` npm package already.

Maybe we can just make the repo name `gnar-cli` here? Or make the npm package called `gnar-node-cli`.

**Comment by alxjrvs** [comment]
After discussing with folks, we decided to keep the repo and package as `gnar-cli`, and make the executable `gnar`. This is in line with a few other packages  that offer a library titled `NAME-cli` and an executable called `NAME`.
