### ISSUE TITLE
Introduce a Changelog

### ISSUE THREAD

**Issue by kevin-j-m** [TheGnarCo/gnar-cli#18]
Once the early development thrash has settled down to some level of stability and core feature set, a changelog should be introduced in Gnar's standard format to keep track of modifications to the repository over time and track releases. See #12.

**Comment by alxjrvs** [comment]
This changelog has been introduced as of #43, and leverages the [automatic changelog utility](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes) in github releases.
