### ISSUE TITLE
Rename repo or binary

### ISSUE THREAD

**Issue by BlakeWilliams** [TheGnarCo/gnar-cli#24]
Sadly `gnar` is taken on NPM and `gnar-cli` installs a binary called `gnar` which is misleading. We could rename the binary to `gnar-cli` but I'm not a huge fan of the trailing`-cli`.

That being said, I was listening to [Behind the Wheel](https://www.youtube.com/watch?v=VEAuMiKqP-4) which gave me some really great [vapor wave](https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/540b0a29856031.561cae68795b5.png) vibes that reminded me of the [Lamborghini Countach](http://imagesvc.timeincapp.com/v3/foundry/image/?q=70&w=1440&url=http%3A%2F%2Fd254andzyoxz3f.cloudfront.net%2Fcountach_hero.jpg) which is one of the most 80's cars ever made.

That all being said, what do folks think of the name `countach`? It's 80's, it's rad, and it means I can over-use emoji like 🕶 and 🌴 .

**Comment by alxjrvs** [comment]
We decided to keep `gnar-cli` as the package name and binary as `gnar`.
